version: "3.5"
services:
  mysql:
    container_name: temporal-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=GoTemporalLoom
    image: mysql
    networks:
      - temporal-network
    ports:
      - 3310:3306
    volumes:
      - /var/lib/mysql
  temporal:
    container_name: temporal
    depends_on:
      - mysql
    environment:
      - DB=mysql8
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=mysql
    image: temporalio/auto-setup:1.24.2
    networks:
      - temporal-network
    ports:
      - 7235:7233

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.24.2-tctl-1.18.1-cli-0.13.0
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.26.2
    networks:
      - temporal-network
    ports:
      - 8200:8080
networks:
  temporal-network:
    driver: bridge
    name: temporal-network